// Generated by gencpp from file global_map/DynamicTrajectoryPoint.msg
// DO NOT EDIT!


#ifndef GLOBAL_MAP_MESSAGE_DYNAMICTRAJECTORYPOINT_H
#define GLOBAL_MAP_MESSAGE_DYNAMICTRAJECTORYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace global_map
{
template <class ContainerAllocator>
struct DynamicTrajectoryPoint_
{
  typedef DynamicTrajectoryPoint_<ContainerAllocator> Type;

  DynamicTrajectoryPoint_()
    : time(0.0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  DynamicTrajectoryPoint_(const ContainerAllocator& _alloc)
    : time(0.0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _time_type;
  _time_type time;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicTrajectoryPoint_

typedef ::global_map::DynamicTrajectoryPoint_<std::allocator<void> > DynamicTrajectoryPoint;

typedef boost::shared_ptr< ::global_map::DynamicTrajectoryPoint > DynamicTrajectoryPointPtr;
typedef boost::shared_ptr< ::global_map::DynamicTrajectoryPoint const> DynamicTrajectoryPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace global_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'global_map': ['/home/djh/ros_example/SCP/src/global_map/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3500997421bb06e40b442d83f83150dc";
  }

  static const char* value(const ::global_map::DynamicTrajectoryPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3500997421bb06e4ULL;
  static const uint64_t static_value2 = 0x0b442d83f83150dcULL;
};

template<class ContainerAllocator>
struct DataType< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "global_map/DynamicTrajectoryPoint";
  }

  static const char* value(const ::global_map::DynamicTrajectoryPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 time\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::global_map::DynamicTrajectoryPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicTrajectoryPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::global_map::DynamicTrajectoryPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::global_map::DynamicTrajectoryPoint_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLOBAL_MAP_MESSAGE_DYNAMICTRAJECTORYPOINT_H
