// Generated by gencpp from file global_map/DynamicObstacles.msg
// DO NOT EDIT!


#ifndef GLOBAL_MAP_MESSAGE_DYNAMICOBSTACLES_H
#define GLOBAL_MAP_MESSAGE_DYNAMICOBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <global_map/DynamicObstacle.h>

namespace global_map
{
template <class ContainerAllocator>
struct DynamicObstacles_
{
  typedef DynamicObstacles_<ContainerAllocator> Type;

  DynamicObstacles_()
    : obstacles()  {
    }
  DynamicObstacles_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::global_map::DynamicObstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::global_map::DynamicObstacle_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::global_map::DynamicObstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::global_map::DynamicObstacles_<ContainerAllocator> const> ConstPtr;

}; // struct DynamicObstacles_

typedef ::global_map::DynamicObstacles_<std::allocator<void> > DynamicObstacles;

typedef boost::shared_ptr< ::global_map::DynamicObstacles > DynamicObstaclesPtr;
typedef boost::shared_ptr< ::global_map::DynamicObstacles const> DynamicObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::global_map::DynamicObstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::global_map::DynamicObstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace global_map

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'global_map': ['/home/djh/ros_example/SCP/src/global_map/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::global_map::DynamicObstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_map::DynamicObstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_map::DynamicObstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_map::DynamicObstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_map::DynamicObstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_map::DynamicObstacles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::global_map::DynamicObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30b207dd63b971b7a3a28ba13f187795";
  }

  static const char* value(const ::global_map::DynamicObstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30b207dd63b971b7ULL;
  static const uint64_t static_value2 = 0xa3a28ba13f187795ULL;
};

template<class ContainerAllocator>
struct DataType< ::global_map::DynamicObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "global_map/DynamicObstacles";
  }

  static const char* value(const ::global_map::DynamicObstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::global_map::DynamicObstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DynamicObstacle[] obstacles\n\
\n\
================================================================================\n\
MSG: global_map/DynamicObstacle\n\
geometry_msgs/Polygon polygon\n\
DynamicTrajectoryPoint[] trajectory\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: global_map/DynamicTrajectoryPoint\n\
float64 time\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::global_map::DynamicObstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::global_map::DynamicObstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DynamicObstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::global_map::DynamicObstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::global_map::DynamicObstacles_<ContainerAllocator>& v)
  {
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::global_map::DynamicObstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLOBAL_MAP_MESSAGE_DYNAMICOBSTACLES_H
